# Generated by Django 3.0.4 on 2020-04-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='nfc_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
