# Generated by Django 3.0.4 on 2020-04-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exhibit_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='audio_en',
            field=models.FileField(blank=True, upload_to='audio/en/'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
